name: KitPvP
version: ${project.version}
main: net.dragonsdoom.metro.kitpvp.KitPvP
authors: [Metro]
description: KitPvP Plugin forked for DragonsDoom
commands:
  kit:
    description: Kit executor, for selecting kits and other things.
  lol:
    description: lol, I don't even know what this is - Pro.
  pvp:
    description: Kit pvp.
  archer:
    description: Kit archer.
  tamer:
    description: Kit tamer.
  pikachu:
    description: Kit pikachu.
  fisherman:
    description: Kit fisherman.
  kangaroo:
    description: Kit kangaroo.
  ghost:
    description: Kit ghost.
  ninja:
    description: Kit ninja.
  hulk:
    description: Kit hulk.
  turtle:
    description: Kit turtle.
  sniper:
    description: Kit sniper.
